[docker] Fix container build
Use local version of chef-base image. Also, note that the local version
of the s2e-chef Dockerfile currently creates the image based on
ayekat/chef-base (as opposed to stefanbucur/chef-base), in order to
avoid out-of-date images, as the versions on the docker hub are not up
to date yet.

diff --git a/docker/doctor b/docker/doctor
--- a/docker/doctor
+++ b/docker/doctor
@@ -1,8 +1,7 @@
 #!/usr/bin/env sh
 
-username="$(id -un)"
-imagename="$username/zopf_base"
 s2e_docker_repo_url='https://github.com/stefanbucur/s2e_docker'
+username="$(id -un)"
 
 # Paths on host:
 runname="$(basename "$0")"         # name of the script
@@ -86,17 +85,19 @@ dr_build()
 		cd -
 	fi
 
-	# Container:
-	cname="$username/zopf:$config"
-	if ! docker inspect "$cname" >/dev/null 2>&1; then
-		printf "\033[1m>>> image $cname not found, building ... %s\033[0m\n" \
-		       '(this may take some time)'
-		docker build --rm --tag="$cname" "$tmppath/s2e_docker/image/chef"
-	else
-		printf "\033[1m>>> image $cname found, not rebuilding\033[0m\n"
-	fi
+	# S²E images:
+	for i in base chef; do
+		dockerimg="$username/s2e-$i"
+		if ! docker inspect "$dockerimg" >/dev/null 2>&1; then
+			printf "\033[1;33m> image $dockerimg not found, building\033[0m\n"
+			docker build --rm --tag="$dockerimg" "$tmppath/s2e_docker/image/$i"
+		else
+			printf "\033[1;32m> image $dockerimg found, not rebuilding\033[0m\n"
+		fi
+	done
 
 	# Run container:
+	cname="$username/s2e-chef"
 	ccmd=$(printf '%s/%s make %s %s' \
 	              "$host_runpath" "$runname" \
 	              "$(test $forcebuild -eq 0 && echo "-f")" $config)
@@ -139,8 +140,7 @@ dr_make()
 	# Configuration:
 	config="$1"
 	case "$config" in
-		debug) builddir='build-debug';;
-		release) builddir='build-release';;
+		debug|release) builddir=build-$config;;
 		*) dr_make_usage;;
 	esac
 	shift
